export const RECORD_BORDER_COLORS: string[] = [
  'red',
  'blue',
  'green',
  'orange',
  'pink',
  'brown',
];

export const BOARD_COLOR_MAP: Record<number, string> = {
  1: 'brown',
  3: 'brown',
  6: 'sky',
  8: 'sky',
  9: 'sky',
  11: 'pink',
  13: 'pink',
  14: 'pink',
  16: 'orange',
  18: 'orange',
  19: 'orange',
  21: 'red',
  23: 'red',
  24: 'red',
  26: 'yellow',
  27: 'yellow',
  29: 'yellow',
  31: 'green',
  32: 'green',
  34: 'green',
  37: 'blue',
  39: 'blue',
};
